---
title: "PACKAGES"
author: "Shakira Babirye"
date: "2024-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Install packages (run only once)

```{r cars}
#install.packages("tidyverse")  # Comprehensive collection of R packages for data manipulation and #visualization
#install.packages("ggplot2")     # For creating visually appealing plots
#install.packages("dplyr")       # For data manipulation tasks
#install.packages("lubridate")   # For working with dates and times
#install.packages("readr")       # For reading data files
#install.packages("reshape2")    # For reshaping data
#install.packages("survival")    # For survival analysis
#install.packages("caret")       # For machine learning tasks
#install.packages("pROC")        # For ROC curve analysis
#install.packages("corrplot")    # For correlation matrix visualization
#install.packages("rmarkdown")   # For creating dynamic documents
#install.packages("car")         # For regression diagnostics and ANOVA
#install.packages("lmtest")      # For diagnostic tests for linear regression models
#install.packages("multcomp")    # For multiple comparison procedures
#install.packages("stats")       # For statistical functions (already installed by default)
#install.packages("readxl")      # For reading Excel files
#install.packages("haven")       # For reading and writing SPSS, Stata, and SAS files
#install.packages("readr")       # For reading various text-based formats like CSV, TSV, and fixed-width files
#install.packages("foreign")     # For reading and writing data stored by Minitab, S, SAS, SPSS, Stata, Systat
#install.packages("rio")         # For importing and exporting data in many formats
#rio::install_formats()

```



# Load packages

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(readr)
library(reshape2)
library(survival)
library(caret)
library(pROC)
library(corrplot)
library(rmarkdown)
library(car)
library(lmtest)
library(multcomp)
library(readxl)
library(haven)
library(readr)
library(foreign)
#library(rio)


```







